Repository UserOfficeProject/user-office-frontend, pull requests merged in 2022-06, with the labels that each got.

#922 feat: Add app settings page where user officer can modify settings. Also included some features page improvements
  cypress/integration/appSettings.ts
  cypress/integration/features.ts
  cypress/integration/generic_templates.ts
  cypress/support/initialDBData.ts
  src/components/App.tsx
  src/components/AppToolbar/AppToolbar.tsx
  src/components/DashBoard.tsx
  src/components/call/CallNotificationAndCycleInfo.tsx
  src/components/call/CallReviewsInfo.tsx
  src/components/menu/MenuItems.tsx
  src/components/questionary/questionaryComponents/DatePicker/QuestionDateForm.tsx
  src/components/questionary/questionaryComponents/DatePicker/QuestionTemplateRelationDateForm.tsx
  src/components/settings/appSettings/AppSettingsPage.tsx
  src/components/settings/appSettings/AppSettingsTable.tsx
  src/components/settings/features/FeaturesTable.tsx
  src/components/theme/theme.tsx
  src/components/user/ExternalAuth.tsx
  src/context/SettingsContextProvider.tsx
  src/generated/sdk.ts
  src/graphql/settings/updateFeatures.graphql
  src/graphql/settings/updateSettings.graphql
  src/hooks/admin/useFormattedDateTime.ts
  src/hooks/admin/useSettings.ts
  src/hooks/common/useDataApi.ts
Labels: enhancement, review: please

#928 feat: Add proposal title in the SEP meeting components modal
  Dockerfile.e2e
  package-lock.json
  package.json
  src/components/SEP/MeetingComponents/ProposalViewModal/SEPMeetingProposalViewModal.tsx
  src/components/proposalBooking/CreateUpdateVisit.tsx
  src/components/questionary/questionaryComponents/MultipleChoice/QuestionaryComponentMultipleChoice.tsx
  src/components/review/AssignTechnicalReview.tsx
  src/generated/sdk.ts
Labels: enhancement, review: please

#929 feat: Use plain textareas for proposal admin comments
  cypress/integration/proposal_administration.ts
  src/components/proposal/ProposalAdmin.tsx
Labels: enhancement

#949 fix: Add missing packages to package-lock
  package-lock.json
Labels: bug, review: please

#944 feat: Upgrade validation package and show characters counter to SEP review comment
  package-lock.json
  package.json
  src/components/review/ProposalGrade.tsx
Labels: enhancement, review: please

#943 feat: Make SEPs visible to SEP_Reviewer with Proposals and assignements tab only
  cypress/integration/SEP.ts
  cypress/integration/generalSeps.ts
  src/components/SEP/MeetingComponents/ProposalViewModal/SEPMeetingProposalViewModal.tsx
  src/components/SEP/Proposals/SEPAssignedReviewersTable.tsx
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx
  src/components/SEP/SEPPage.tsx
  src/components/menu/MenuItems.tsx
  src/context/ReviewAndAssignmentContextProvider.tsx
  src/generated/sdk.ts
  src/graphql/SEP/getSEPProposal.graphql
  src/graphql/SEP/getSEPProposals.graphql
  src/hooks/SEP/useSEPProposalData.ts
Labels: enhancement, review: please

#926 fix(templates): Should be able to delete active template
  cypress/integration/templates.ts
  src/components/template/TemplatesTable.tsx
  src/components/template/withMarkTemplateAsActiveAction.tsx
Labels: bug, review: please

#931 feat(shipping): improve shipping instructions
  src/components/questionary/questionaryComponents/QuestionnairesList.tsx
  src/components/shipments/DeclareShipments.tsx
  src/components/shipments/ShippingInstructions.tsx
Labels: enhancement

#921 fix(questionary): fixing missing validation for question template relation
  cypress/fixtures/template_export.json
  cypress/integration/templates.ts
  src/components/questionary/questionaryComponents/Boolean/QuestionTemplateRelationBooleanForm.tsx
  src/components/questionary/questionaryComponents/Embellishment/QuestionTemplateRelationEmbellishmentForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionTemplateRelationFileUploadForm.tsx
  src/components/questionary/questionaryComponents/GenericTemplate/QuestionTemplateRelationGenericTemplateForm.tsx
  src/components/questionary/questionaryComponents/GenericTemplateBasis/QuestionTemplateRelationGenericTemplateBasisForm.tsx
  src/components/questionary/questionaryComponents/Interval/QuestionTemplateRelationIntervalForm.tsx
  src/components/questionary/questionaryComponents/MultipleChoice/QuestionTemplateRelationMultipleChoiceForm.tsx
  src/components/questionary/questionaryComponents/NumberInput/QuestionTemplateRelationNumberInputForm.tsx
  src/components/questionary/questionaryComponents/RichTextInput/QuestionTemplateRelationRichTextInputForm.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/QuestionTemplateRelationSampleDeclarationForm.tsx
  src/components/questionary/questionaryComponents/TextInput/QuestionTemplateRelationTextInputForm.tsx
Labels: bug, review: please

#947 feat: Add page limit for PDF file uploads
  cypress/fixtures/pdf_3_pages.pdf
  cypress/fixtures/pdf_5_pages.pdf
  cypress/fixtures/template_export.json
  cypress/integration/templates.ts
  cypress/support/template.ts
  src/components/common/FileUploadComponent.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionFileUploadForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionTemplateRelationFileUploadForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionaryComponentFileUpload.tsx
  src/components/review/ProposalTechnicalReview.tsx
  src/generated/sdk.ts
  src/graphql/template/fragment.fieldConfig.graphql
Labels: enhancement, review: please

#957 Release 23 06 2022
  cypress/fixtures/pdf_3_pages.pdf
  cypress/fixtures/pdf_5_pages.pdf
  cypress/fixtures/template_export.json
  cypress/integration/SEP.ts
  cypress/integration/generalSeps.ts
  cypress/integration/settings.ts
  cypress/integration/templates.ts
  cypress/package-lock.json
  cypress/package.json
  cypress/support/template.ts
  package-lock.json
  package.json
  src/components/SEP/MeetingComponents/ProposalViewModal/SEPMeetingProposalViewModal.tsx
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
  src/components/SEP/Proposals/SEPAssignedReviewersTable.tsx
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx
  src/components/SEP/SEPPage.tsx
  src/components/common/FileUploadComponent.tsx
  src/components/menu/MenuItems.tsx
  src/components/questionary/questionaryComponents/Boolean/QuestionTemplateRelationBooleanForm.tsx
  src/components/questionary/questionaryComponents/Embellishment/QuestionTemplateRelationEmbellishmentForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionFileUploadForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionTemplateRelationFileUploadForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionaryComponentFileUpload.tsx
  src/components/questionary/questionaryComponents/GenericTemplate/QuestionTemplateRelationGenericTemplateForm.tsx
  src/components/questionary/questionaryComponents/GenericTemplateBasis/QuestionTemplateRelationGenericTemplateBasisForm.tsx
  src/components/questionary/questionaryComponents/Interval/QuestionTemplateRelationIntervalForm.tsx
  src/components/questionary/questionaryComponents/MultipleChoice/QuestionTemplateRelationMultipleChoiceForm.tsx
  src/components/questionary/questionaryComponents/NumberInput/QuestionTemplateRelationNumberInputForm.tsx
  src/components/questionary/questionaryComponents/QuestionnairesList.tsx
  src/components/questionary/questionaryComponents/RichTextInput/QuestionTemplateRelationRichTextInputForm.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/QuestionTemplateRelationSampleDeclarationForm.tsx
  src/components/questionary/questionaryComponents/TextInput/QuestionTemplateRelationTextInputForm.tsx
  src/components/review/ProposalGrade.tsx
  src/components/review/ProposalTechnicalReview.tsx
  src/components/shipments/DeclareShipments.tsx
  src/components/shipments/ShippingInstructions.tsx
  src/components/template/TemplatesTable.tsx
  src/components/template/withMarkTemplateAsActiveAction.tsx
  src/components/user/PeopleTable.tsx
  src/components/visit/CreateVisitRegistration.tsx
  src/context/ReviewAndAssignmentContextProvider.tsx
  src/generated/sdk.ts
  src/graphql/SEP/getSEPProposal.graphql
  src/graphql/SEP/getSEPProposals.graphql
  src/graphql/template/fragment.fieldConfig.graphql
  src/graphql/user/fragment.basicUserInformation.graphql
  src/hooks/SEP/useSEPProposalData.ts
  src/utils/withConfirm.tsx
Labels: review: please

#951 feat: Add more information to instrument scientists view of proposal
  cypress/integration/templates.ts
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/review/ProposalQuestionaryReview.tsx
  src/components/review/ProposalReviewContent.tsx
  src/components/visit/CreateVisitRegistration.tsx
  src/generated/sdk.ts
  src/graphql/user/fragment.basicUserInformation.graphql
  src/utils/user.ts
Labels: enhancement, review: please
