Repository UserOfficeProject/user-office-frontend, pull requests merged in 2022-04, with the labels that each got.

#842 fix: SEP reviewer should only see list of proposals he/she can review
  cypress/integration/SEP.ts
  src/components/review/ProposalTableReviewer.tsx
  src/generated/sdk.ts
  src/graphql/review/getReview.graphql
  src/hooks/review/useReviewData.ts
Labels: bug

#843 fix(review): Comment for grade should be mandatory
  cypress/integration/SEP.ts
  package-lock.json
  package.json
  src/components/common/ErrorMessage.tsx
  src/components/review/ProposalGrade.tsx
  src/components/review/ProposalTableReviewer.tsx
Labels: bug

#846 chore: revert lint optimization
  package.json
Labels: chore

#849 fix: update dockerfiles
  Dockerfile
  Dockerfile.dev
Labels: bug

#850 fix: remove YUP limit for comment input
  cypress/integration/SEP.ts
  package-lock.json
  package.json
Labels: bug

#819 feat(technical reviews): Bulk submit for technical reviews as instrument scientists and refactor/improve the SEP reviewer proposal table
  cypress/integration/SEP.ts
  cypress/integration/instruments.ts
  cypress/support/sep.ts
  cypress/types/sep.d.ts
  package-lock.json
  package.json
  src/components/common/ErrorMessage.tsx
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/questionary/questionaryComponents/QuestionnairesList.tsx
  src/components/review/ProposalGrade.tsx
  src/components/review/ProposalTableReviewer.tsx
  src/components/review/ProposalTechnicalReview.tsx
  src/generated/sdk.ts
  src/graphql/proposal/getInstrumentScientistProposals.graphql
  src/graphql/review/submitTechnicalReview.graphql
  src/graphql/review/submitTechnicalReviews.graphql
Labels: enhancement, review: please

#854 test(SEP reviews): Improve SEP reviewer bulk submission e2e test
  cypress/integration/SEP.ts
  src/components/review/ProposalGrade.tsx
Labels: test

#851 feat: adding info that there is no guide
  src/components/pages/GradeGuidePage.tsx
Labels: enhancement

#787 feat: Show experiment times
  cypress/integration/experiments.ts
  cypress/integration/proposal_esi.ts
  cypress/integration/shipments.ts
  cypress/integration/visits.ts
  cypress/support/utils.ts
  cypress/types/utils.d.ts
  src/components/DashBoard.tsx
  src/components/common/SuperMaterialTable.tsx
  src/components/experiment/DateFilter.tsx
  src/components/experiment/ExperimentFilterBar.tsx
  src/components/experiment/ExperimentPage.tsx
  src/components/experiment/ExperimentTable.tsx
  src/components/experiment/ExperimentUrlQueryParamsType.ts
  src/components/experiment/ExperimentVisitsTable.tsx
  src/components/experiment/PresetDateSelector.tsx
  src/components/menu/MenuItems.tsx
  src/components/proposalBooking/CreateUpdateVisit.tsx
  src/components/questionary/questionaryComponents/DatePicker/DateSearchCriteriaInput.tsx
  src/components/questionary/questionaryComponents/ProposalEsiBasis/ProposalEsiDetailsButton.tsx
  src/generated/sdk.ts
  src/graphql/scheduledEvent/getScheduledEventWithShipments.out
  src/graphql/scheduledEvent/getScheduledEventsCore.graphql
  src/hooks/common/ButtonWithDialog.tsx
  src/hooks/proposalBooking/useActionButtons.tsx
  src/hooks/scheduledEvent/useScheduledEvents.ts
Labels: enhancement

#830 refactor(formik components): Use existing formik-mui components instead of defining custom ones
  cypress/integration/SEP.ts
  cypress/integration/instruments.ts
  cypress/integration/proposal_administration.ts
  cypress/integration/proposals.ts
  cypress/integration/settings.ts
  cypress/integration/templates.ts
  cypress/integration/user_spec.ts
  cypress/support/initialDBData.ts
  src/components/SEP/MeetingComponents/ProposalViewModal/FinalRankingForm.tsx
  src/components/SEP/Proposals/AssignProposalsToSEP.tsx
  src/components/call/CallGeneralInfo.tsx
  src/components/call/CreateUpdateCall.tsx
  src/components/common/FormikDropdown.tsx
  src/components/common/FormikUIAutocomplete.tsx
  src/components/common/FormikUICustomCheckbox.tsx
  src/components/common/FormikUICustomSelect.tsx
  src/components/common/Query.tsx
  src/components/common/withPreventSubmit.tsx
  src/components/instrument/AssignProposalsToInstrument.tsx
  src/components/instrument/CreateUpdateInstrument.tsx
  src/components/proposal/CallSelectModalOnProposalClone.tsx
  src/components/proposal/ChangeProposalStatus.tsx
  src/components/proposal/ProposalAdmin.tsx
  src/components/proposalBooking/CreateUpdateVisit.tsx
  src/components/questionary/questionaryComponents/Boolean/QuestionBooleanForm.tsx
  src/components/questionary/questionaryComponents/Boolean/QuestionTemplateRelationBooleanForm.tsx
  src/components/questionary/questionaryComponents/DatePicker/QuestionDateForm.tsx
  src/components/questionary/questionaryComponents/DatePicker/QuestionTemplateRelationDateForm.tsx
  src/components/questionary/questionaryComponents/Embellishment/QuestionEmbellishmentForm.tsx
  src/components/questionary/questionaryComponents/Embellishment/QuestionTemplateRelationEmbellishmentForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionFileUploadForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionTemplateRelationFileUploadForm.tsx
  src/components/questionary/questionaryComponents/Interval/QuestionIntervalForm.tsx
  src/components/questionary/questionaryComponents/Interval/QuestionTemplateRelationIntervalForm.tsx
  src/components/questionary/questionaryComponents/MultipleChoice/QuestionMultipleChoiceForm.tsx
  src/components/questionary/questionaryComponents/MultipleChoice/QuestionTemplateRelationMultipleChoiceForm.tsx
  src/components/questionary/questionaryComponents/NumberInput/QuestionNumberInputForm.tsx
  src/components/questionary/questionaryComponents/NumberInput/QuestionTemplateRelationNumberInputForm.tsx
  src/components/questionary/questionaryComponents/RichTextInput/QuestionRichTextInputForm.tsx
  src/components/questionary/questionaryComponents/RichTextInput/QuestionTemplateRelationRichTextInputForm.tsx
  src/components/questionary/questionaryComponents/TextInput/QuestionTemplateRelationTextInputForm.tsx
  src/components/questionary/questionaryComponents/TextInput/QuestionTextInputForm.tsx
  src/components/review/ProposalGrade.tsx
  src/components/review/ProposalTechnicalReview.tsx
  src/components/settings/proposalWorkflow/AddNewWorkflowConnectionsRow.tsx
  src/components/shipments/DeclareShipments.tsx
  src/components/user/SignUp.tsx
  src/components/user/UpdateUserInformation.tsx
  src/utils/utilTypes.ts
  src/utils/withConfirm.tsx
Labels: refactor

#857 feat: Adding recommendation column and expanding view
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
  src/components/SEP/SEPPage.tsx
  src/components/experiment/ExperimentTable.tsx
  src/components/proposal/ProposalPage.tsx
  src/components/template/TemplateEditor.tsx
Labels: enhancement

#691 feat: Add country to institution
  cypress/integration/institutions.ts
  src/components/institution/CreateUpdateInstitution.tsx
  src/components/institution/InstitutionTable.tsx
  src/components/institution/MergeInstitutionPage.tsx
  src/components/user/SignUp.tsx
  src/components/user/UpdateUserInformation.tsx
  src/generated/sdk.ts
  src/graphql/admin/country.fragment.graphql
  src/graphql/admin/createInstitution.graphql
  src/graphql/admin/getInstitutionsWithCountry.graphql
  src/graphql/admin/mergeInstitutions.graphql
  src/graphql/admin/updateInstitution.graphql
  src/graphql/user/getFields.graphql
  src/hooks/admin/useInstitutionData.ts
Labels: enhancement

#856 feat: use the call allocation time unit everywhere where time is used and fix some logic to improve functionality
  cypress/integration/SEP.ts
  cypress/integration/calls.ts
  cypress/integration/instruments.ts
  cypress/integration/proposal_administration.ts
  cypress/support/initialDBData.ts
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
  src/components/SEP/MeetingComponents/SEPMeetingComponentsView.tsx
  src/components/SEP/MeetingComponents/SEPMeetingInstrumentsTable.tsx
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsView.tsx
  src/components/call/AssignedInstrumentsTable.tsx
  src/components/common/proposalFilters/CallFilter.tsx
  src/components/experiment/ExperimentFilterBar.tsx
  src/components/questionary/questionaryComponents/Interval/QuestionaryComponentInterval.tsx
  src/components/questionary/questionaryComponents/NumberInput/QuestionaryComponentNumberInput.tsx
  src/generated/sdk.ts
  src/graphql/SEP/getSEPProposals.graphql
  src/hooks/SEP/useSEPProposalsByInstrument.ts
  src/hooks/SEP/useSEPProposalsData.ts
  src/hooks/instrument/useInstrumentsBySEPData.ts
Labels: enhancement

#860 fix: Fix ranking in SEP meeting
  cypress/integration/SEP.ts
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
Labels: bug

#853 feat: Group questions in review by topic
  cypress/integration/scheduler.ts
  cypress/integration/templates.ts
  src/components/proposal/ProposalContainer.tsx
  src/components/proposal/ProposalEdit.tsx
  src/components/proposal/ProposalQuestionaryDetails.tsx
  src/components/proposal/ProposalSummary.tsx
  src/components/questionary/AnswersTable.tsx
  src/components/questionary/DefaultReviewWizardStep.ts
  src/components/questionary/DefaultStepDisplayElementFactory.tsx
  src/components/questionary/NavigationFragment.tsx
  src/components/questionary/QuestionaryDetails.tsx
  src/components/questionary/StepView.tsx
  src/components/questionary/createDefaultReviewWizardStep.ts
  src/components/questionary/questionaries/proposal/ProposalQuestionaryDefinition.ts
  src/components/questionary/questionaries/sampleEsi/SampleEsiQuestionaryDefinition.ts
  src/components/questionary/questionaries/shipment/ShipmentQuestionaryDefinition.ts
  src/components/questionary/questionaries/visitRegistration/VisitRegistrationQuestionaryDefinition.ts
  src/components/questionary/questionaryComponents/RichTextInput/RichTextInputRenderer.tsx
  src/components/review/ProposalGrade.tsx
  src/models/questionary/StepType.ts
  src/utils/addElipsis.ts
  src/utils/stripHtml.ts
Labels: enhancement, review: please

#863 Refactor: Added warning to changing user roles
  cypress/integration/personal_information.ts
  cypress/support/utils.ts
  cypress/types/utils.d.ts
  src/components/user/UpdateUserRoles.tsx
  src/utils/useDataApiWithFeedback.ts
Labels: review: please, refactor

#840 feat: hide technical review and instrument management features
  src/components/DashBoard.tsx
  src/components/menu/MenuItems.tsx
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/review/ProposalReviewContent.tsx
  src/generated/sdk.ts
Labels: enhancement, review: please

#859 feat: Add bulk download and removal of proposals in SEP proposals and assignments view
  cypress/integration/SEP.ts
  cypress/integration/settings.ts
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx
  src/utils/withConfirm.tsx
Labels: enhancement, review: please

#861 feat: Add reviewer in the ProposalsFilter to be able to filter only logged in user reviews
  cypress/integration/instruments.ts
  cypress/integration/proposal_administration.ts
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx
  src/components/common/FormikUIAutocomplete.tsx
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/proposal/ProposalTableOfficer.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/QuestionSampleDeclarationForm.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/QuestionTemplateRelationSampleDeclarationForm.tsx
  src/components/review/ProposalTableReviewer.tsx
  src/components/review/ReviewerFilter.tsx
  src/components/sample/SampleSafetyPage.tsx
  src/generated/sdk.ts
  src/hooks/proposal/useProposalsCoreData.ts
Labels: enhancement, review: please

#869 fix: Reorder information in the modal for SEP meeting components where the more important details come first
  src/components/SEP/MeetingComponents/ProposalViewModal/SEPMeetingProposalViewModal.tsx
Labels: bug

#870 feat: Improve UX for reordering of the meeting component proposals. No spinner is shown anymore
  cypress/integration/SEP.ts
  src/components/AppToolbar/RoleSelection.tsx
  src/components/SEP/General/AddSEP.tsx
  src/components/SEP/General/SEPGeneralInfo.tsx
  src/components/SEP/MeetingComponents/ProposalViewModal/FinalRankingForm.tsx
  src/components/SEP/MeetingComponents/ProposalViewModal/TechnicalReviewInfo.tsx
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
  src/components/SEP/MeetingComponents/SEPMeetingInstrumentsTable.tsx
  src/components/SEP/Members/SEPMembers.tsx
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx
  src/components/SEP/SEPsTable.tsx
  src/components/call/AssignInstrumentsToCall.tsx
  src/components/call/AssignedInstrumentsTable.tsx
  src/components/call/CallsTable.tsx
  src/components/call/CreateUpdateCall.tsx
  src/components/institution/CreateUpdateInstitution.tsx
  src/components/institution/InstitutionTable.tsx
  src/components/institution/MergeInstitutionPage.tsx
  src/components/instrument/AssignedScientistsTable.tsx
  src/components/instrument/CreateUpdateInstrument.tsx
  src/components/instrument/InstrumentTable.tsx
  src/components/pages/PageInputBox.tsx
  src/components/proposal/ProposalAdmin.tsx
  src/components/proposal/ProposalTable.tsx
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/proposal/ProposalTableOfficer.tsx
  src/components/proposalBooking/CreateUpdateVisit.tsx
  src/components/questionary/QuestionaryStepView.tsx
  src/components/review/AssignTechnicalReview.tsx
  src/components/review/ProposalGrade.tsx
  src/components/review/ProposalTableReviewer.tsx
  src/components/review/ProposalTechnicalReview.tsx
  src/components/sample/SampleSafetyPage.tsx
  src/components/settings/apiAccessTokens/ApiAccessTokensTable.tsx
  src/components/settings/apiAccessTokens/CreateUpdateApiAccessToken.tsx
  src/components/settings/proposalStatus/CreateUpdateProposalStatus.tsx
  src/components/settings/proposalStatus/ProposalStatusesTable.tsx
  src/components/settings/proposalWorkflow/CreateProposalWorkflow.tsx
  src/components/settings/proposalWorkflow/ProposalWorkflowsTable.tsx
  src/components/settings/unitList/CreateUnit.tsx
  src/components/settings/unitList/UnitTable.tsx
  src/components/template/QuestionsPage.tsx
  src/components/template/TemplatesTable.tsx
  src/components/template/import/MergeReview.tsx
  src/components/user/InviteUserForm.tsx
  src/components/user/PeoplePage.tsx
  src/components/user/UpdatePassword.tsx
  src/components/user/UpdateUserInformation.tsx
  src/components/user/UpdateUserRoles.tsx
  src/hooks/settings/usePersistProposalWorkflowEditorModel.ts
  src/units/UnitMergeReview.tsx
  src/utils/useDataApiWithFeedback.ts
Labels: enhancement, review: please

#865 fix(template questions): make max files required on file upload question and improve some UI
  cypress/integration/templates.ts
  src/components/SEP/MeetingComponents/ProposalViewModal/FinalRankingForm.tsx
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
  src/components/SEP/MeetingComponents/SEPMeetingInstrumentsTable.tsx
  src/components/SEP/Members/SEPMembers.tsx
  src/components/SEP/SEPsTable.tsx
  src/components/common/FileUploadComponent.tsx
  src/components/common/NavigButton.tsx
  src/components/institution/InstitutionTable.tsx
  src/components/institution/MergeInstitutionPage.tsx
  src/components/pages/GradeGuidePage.tsx
  src/components/proposal/ProposalSummary.tsx
  src/components/proposal/ProposalTableOfficer.tsx
  src/components/questionary/NavigationFragment.tsx
  src/components/questionary/QuestionaryDetails.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionFileUploadForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionTemplateRelationFileUploadForm.tsx
  src/components/review/ProposalGrade.tsx
  src/components/user/SignUp.tsx
  src/components/user/UpdateUserInformation.tsx
  src/hooks/admin/useInstitutionData.ts
  src/hooks/common/ButtonWithDialog.tsx
Labels: bug, review: please

#868 fix: Remove time from date assigned column and use just date format
  src/components/SEP/Proposals/SEPAssignedReviewersTable.tsx
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx
Labels: bug

#877 fix: Improve shipment declaration UI
  src/components/shipments/DeclareShipments.tsx
  src/components/shipments/ShipmentReview.tsx
Labels: bug

#867 fix(password confirmation): make password confirmation required and update the schema to check equality
  cypress/integration/user_spec.ts
  package-lock.json
  package.json
  src/components/user/SignUp.tsx
  src/components/user/UpdatePassword.tsx
Labels: bug, review: please
