Repository UserOfficeProject/user-office-frontend, pull requests merged in 2022-02, with the labels that each got.

#745 Fix-stfc-call-creation-issue
  src/components/call/CreateUpdateCall.tsx
  src/components/common/MultistepWizard.tsx
  src/generated/sdk.ts
Labels: review: please

#744 chore(npm): Lock down node version to 16
  .npmrc
  package-lock.json
  package.json
Labels: chore

#727 fix(shipments): Add ability to declare multiple shipments per experiment time
  cypress/integration/shipments.ts
  cypress/integration/visits.ts
  src/components/DashBoard.tsx
  src/components/questionary/questionaryComponents/QuestionnairesList.tsx
  src/components/questionary/questionaryComponents/QuestionnairesListItem.tsx
  src/components/shipments/CreateShipment.tsx
  src/components/shipments/CreateUpdateShipment.tsx
  src/components/shipments/DeclareShipments.tsx
  src/components/shipments/DeclareShipmentsPage.tsx
  src/components/shipments/UpdateShipment.tsx
  src/generated/sdk.ts
  src/graphql/scheduledEvent/fragment.scheduledEventCore.graphql
  src/graphql/scheduledEvent/getScheduledEventCore.graphql
  src/graphql/scheduledEvent/getScheduledEventWithShipments.out
  src/hooks/proposalBooking/useActionButtons.tsx
  src/hooks/scheduledEvent/useScheduledEvent.ts
  src/hooks/scheduledEvent/useScheduledEventWithShipments.txt
  src/hooks/shipment/useBlankShipment.ts
  src/hooks/shipment/useShipments.ts
  src/utils/withConfirm.tsx
Labels: bug

#749 Added fullWidth property to principal investigator field
  src/components/proposal/ProposalParticipant.tsx
Labels: review: please

#752 fix(templates): Adding multiple choice question answer items
  cypress/support/template.ts
  src/components/common/FormikUICustomTable.tsx
Labels: bug

#753 fix(template): Changing template metadata throws an exception
  cypress/integration/templates.ts
  src/components/template/TemplateMetadataEditor.tsx
  src/models/questionary/QuestionaryEditorModel.ts
Labels: bug, review: please

#751 feat(question): Trim whitespace when searching questions
  cypress/integration/questions.ts
  cypress/support/initialDBData.ts
  src/components/template/QuestionsPage.tsx
  src/components/template/QuestionsTableFilter.tsx
Labels: enhancement, review: please

#758 refactor(SEP e2e tests): Make SEP e2e tests more stable
  cypress/integration/SEP.ts
  package-lock.json
Labels: review: please, refactor

#762 fix(instrument scientist): Small GUI fixes for instrument scientist view
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/generated/sdk.ts
Labels: bug

#755 Update page title
  cypress/integration/settings.ts
  src/components/AppToolbar/AppToolbar.tsx
  src/components/DashBoard.tsx
  src/components/TitledRoute.tsx
  src/components/settings/proposalWorkflow/ProposalWorkflowMetadataEditor.tsx
Labels: type: feature, review: please, origin: project

#765 refactor: remove unused commissioning booking type from scheduler
  src/generated/sdk.ts
Labels: refactor

#770 test(instruments): e2e test for bugfix about showing the right icon on view/edit proposal inside instrument scientist table
  cypress/integration/instruments.ts
  src/components/proposal/ProposalTableInstrumentScientist.tsx
Labels: review: please, test
