Repository UserOfficeProject/user-office-frontend, pull requests merged in 2022-01, with the labels that each got.

#698 Added check for reference text
  src/components/proposal/ProposalTable.tsx
  src/components/proposal/ProposalTableUser.tsx
Labels: review: please

#722 fix: validation for spinner arrows in firefox
  src/components/questionary/questionaryComponents/NumberInput/QuestionaryComponentNumberInput.tsx
Labels: bug, review: please

#711 fix(shipment): Attach shipment to scheduld event
  cypress/integration/visits.ts
  src/components/questionary/questionaryComponents/ShipmentBasis/QuestionaryComponentShipmentBasis.tsx
  src/components/shipments/CreateShipment.tsx
  src/components/shipments/CreateUpdateShipment.tsx
  src/generated/sdk.ts
  src/graphql/proposalBooking/getUserProposalBookingsWithEvents.graphql
  src/graphql/shipment/createShipment.graphql
  src/graphql/shipment/fragment.shipment.graphql
  src/graphql/visit/createVisit.graphql
  src/graphql/visit/updateVisit.graphql
  src/hooks/proposalBooking/useActionButtons.tsx
  src/hooks/proposalBooking/useProposalBookingsScheduledEvents.ts
Labels: bug

#716 refactor(questionary): Refactor questionary events
  src/components/feedback/FeedbackContainer.tsx
  src/components/feedback/FeedbackReview.tsx
  src/components/proposal/ProposalContainer.tsx
  src/components/proposal/ProposalSummary.tsx
  src/components/proposalEsi/ProposalEsiContainer.tsx
  src/components/proposalEsi/ProposalEsiReview.tsx
  src/components/questionary/questionaries/genericTemplate/GenericTemplateStepDisplayElementFactory.tsx
  src/components/questionary/questionaries/sample/SampleStepDisplayElementFactory.tsx
  src/components/questionary/questionaryComponents/FeedbackBasis/QuestionaryComponentFeedbackBasis.tsx
  src/components/questionary/questionaryComponents/GenericTemplate/GenericTemplateContainer.tsx
  src/components/questionary/questionaryComponents/GenericTemplateBasis/QuestionaryComponentGenericTemplateBasis.tsx
  src/components/questionary/questionaryComponents/ProposalBasis/QuestionaryComponentProposalBasis.tsx
  src/components/questionary/questionaryComponents/ProposalEsiBasis/QuestionaryComponentProposalEsiBasis.tsx
  src/components/questionary/questionaryComponents/SampleBasis/QuestionaryComponentSampleBasis.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/SampleDeclarationContainer.tsx
  src/components/questionary/questionaryComponents/ShipmentBasis/QuestionaryComponentShipmentBasis.tsx
  src/components/questionary/questionaryComponents/VisitBasis/QuestionaryComponentVisitBasis.tsx
  src/components/sampleEsi/SampleEsiContainer.tsx
  src/components/sampleEsi/SampleEsiReview.tsx
  src/components/shipments/ShipmentContainer.tsx
  src/components/shipments/ShipmentReview.tsx
  src/components/visit/VisitRegistrationContainer.tsx
  src/components/visit/VisitRegistrationReview.tsx
  src/hooks/proposal/usePersistProposalModel.ts
  src/models/questionary/QuestionarySubmissionState.ts
Labels: refactor

#729 fix(scheduled-events): Update SDK
  src/generated/sdk.ts
Labels: bug

#720 refactor(questionary): Refactor QuestionaryContainer and QuestionarySubmissionModel
  src/components/feedback/CreateFeedback.tsx
  src/components/feedback/FeedbackContainer.tsx
  src/components/feedback/UpdateFeedback.tsx
  src/components/proposal/ProposalContainer.tsx
  src/components/proposalBooking/CheckBadge.tsx
  src/components/proposalBooking/DotBadge.tsx
  src/components/proposalEsi/CreateProposalEsi.tsx
  src/components/proposalEsi/ProposalEsiContainer.tsx
  src/components/proposalEsi/UpdateProposalEsi.tsx
  src/components/questionary/Questionary.tsx
  src/components/questionary/QuestionaryRegistry.tsx
  src/components/questionary/QuestionaryStepView.tsx
  src/components/questionary/questionaries/esi/EsiQuestionaryDefinition.ts
  src/components/questionary/questionaries/feedback/FeedbackQuestionaryDefinition.ts
  src/components/questionary/questionaries/genericTemplate/GenericTemplateQuestionaryDefinition.ts
  src/components/questionary/questionaries/proposal/ProposalQuestionaryDefinition.ts
  src/components/questionary/questionaries/sample/SampleQuestionaryDefinition.ts
  src/components/questionary/questionaries/sampleEsi/SampleEsiQuestionaryDefinition.ts
  src/components/questionary/questionaries/shipment/ShipmentQuestionaryDefinition.ts
  src/components/questionary/questionaries/visitRegistration/VisitRegistrationQuestionaryDefinition.ts
  src/components/questionary/questionaryComponents/GenericTemplate/GenericTemplateContainer.tsx
  src/components/questionary/questionaryComponents/ProposalEsiBasis/EditProposalSamples.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/SampleDeclarationContainer.tsx
  src/components/sampleEsi/SampleEsiContainer.tsx
  src/components/shipments/CreateShipment.tsx
  src/components/shipments/ShipmentContainer.tsx
  src/components/visit/CreateUpdateVisitRegistration.tsx
  src/components/visit/CreateVisitRegistration.tsx
  src/components/visit/UpdateVisitRegistration.tsx
  src/components/visit/VisitRegistrationContainer.tsx
  src/models/questionary/QuestionarySubmissionState.ts
  src/models/questionary/createCustomEventHandlers.ts
  src/models/questionary/feedback/FeedbackSubmissionState.ts
  src/models/questionary/genericTemplate/GenericTemplateSubmissionState.ts
  src/models/questionary/proposal/ProposalSubmissionState.ts
  src/models/questionary/proposalEsi/ProposalEsiSubmissionState.ts
  src/models/questionary/sample/SampleSubmissionState.ts
  src/models/questionary/sampleEsi/SampleEsiSubmissionState.ts
  src/models/questionary/shipment/ShipmentSubmissionState.ts
  src/models/questionary/useEventHandlers.ts
  src/models/questionary/visit/VisitRegistrationSubmissionState.ts
  src/utils/json.ts
Labels: refactor

#739 Run dev Docker container as Node user
  Dockerfile.dev
Labels: review: please

#731 SWAP-2179-improve-call-modal-loading-on-open
  src/components/call/CallGeneralInfo.tsx
  src/components/call/CreateUpdateCall.tsx
  src/hooks/call/useCallTemplates.ts
Labels: review: please

#742 Swap 2134 - Remove unused code & dependencies
  .unimportedrc.json
  package-lock.json
  package.json
  src/components/pages/FooterContent.tsx
  src/components/questionary/questionaryComponents/ProposalEsiBasis/EditProposalSamples.tsx
  src/components/shipments/CreateShipment.tsx
  src/context/UserContextProvider.tsx
  src/hooks/common/usePrevious.ts
  src/hooks/genericTemplate/useDownloadPDFGenericTemplate.ts
  src/hooks/genericTemplate/useGenericTemplatesWithProposalData.ts
  src/hooks/genericTemplate/useProposalGenericTemplates.ts
  src/hooks/proposal/useMyProposals.ts
  src/hooks/proposalBooking/useActionButtons.tsx
  src/hooks/questionary/QuestionaryUIStep.ts
  src/hooks/sample/useSamplesWithProposalData.ts
  src/hooks/shipment/useMyShipments.ts
  src/hooks/template/useDownloadTemplate.ts
  src/hooks/template/useProposalTemplates.ts
  src/hooks/visit/useVisit.ts
  src/models/Review.ts
  src/models/User.ts
  src/models/countries-abbrevation.ts
  src/models/questionary/feedback/FeedbackCore.ts
  src/models/questionary/genericTemplate/GenericTemplateWithProposalData.ts
  src/models/questionary/proposalEsi/ProposalEsiCore.ts
  src/models/questionary/sampleEsi/SampleEsiCore.ts
  src/setupProxy.js
  src/utils/FormikAsyncFormHandler.ts
Labels: review: please
