Repository UserOfficeProject/user-office-frontend, pull requests merged in 2022-07, with the labels that each got.

#962 refactor: import faker from fork UserOfficeProject/user-office-projec…
  cypress/integration/SEP.ts
  cypress/integration/calls.ts
  cypress/integration/eventLogs.ts
  cypress/integration/generalSeps.ts
  cypress/integration/generic_templates.ts
  cypress/integration/institutions.ts
  cypress/integration/instruments.ts
  cypress/integration/pages.ts
  cypress/integration/peopleTable.ts
  cypress/integration/personal_information.ts
  cypress/integration/proposal_administration.ts
  cypress/integration/proposal_esi.ts
  cypress/integration/proposals.ts
  cypress/integration/questions.ts
  cypress/integration/samples.ts
  cypress/integration/settings.ts
  cypress/integration/shipments.ts
  cypress/integration/templates.ts
  cypress/integration/units.ts
  cypress/integration/user_administration.ts
  cypress/integration/user_spec.ts
  cypress/integration/visits.ts
  cypress/package-lock.json
  cypress/package.json
  package-lock.json
  package.json
Labels: review: please, refactor

#960 feat: Add seps to a call
  cypress/integration/calls.ts
  src/components/call/CallReviewsInfo.tsx
  src/components/call/CallsTable.tsx
  src/components/call/CreateUpdateCall.tsx
  src/components/common/FormikUIAutocomplete.tsx
  src/generated/sdk.ts
  src/graphql/call/createCall.graphql
  src/graphql/call/fragment.call.graphql
  src/graphql/call/updateCall.graphql
Labels: enhancement

#973 refactor(questionary): move custom reducer logic
  src/components/proposal/ProposalContainer.tsx
  src/models/questionary/QuestionarySubmissionState.ts
Labels: refactor

#974 refactor: Mark short code label as public
  src/components/call/CallGeneralInfo.tsx
Labels: review: please, refactor

#972 fix(instrument scientist): Show disabled Admin tab form for instrument scientst
  cypress/integration/instruments.ts
  src/components/proposal/ProposalAdmin.tsx
Labels: bug, review: please
