Repository UserOfficeProject/user-office-frontend, pull requests merged in 2022-08, with the labels that each got.

#971 626 arrows on mcq question duplicate selected option
  cypress/integration/templates.ts
  src/components/common/FormikUICustomTable.tsx
Labels: review: please

#976 644 multiple choice question not updating
  cypress/integration/templates.ts
  src/components/common/FormikUICustomTable.tsx
Labels: review: please

#979 635 co proposers update box is hidden
  src/components/user/PeopleTable.tsx
  src/components/user/ProposalsPeopleTable.tsx
Labels: review: please

#982 #631: External auth logout doesn't work in Firefox
  src/context/UserContextProvider.tsx
Labels: review: please, 631

#964 feat: Add questionary preview for proposal templates
  cypress/integration/templates.ts
  src/components/proposal/ProposalContainer.tsx
  src/components/proposal/ProposalCreate.tsx
  src/components/questionary/Questionary.tsx
  src/components/questionary/questionaries/sample/SampleQuestionaryDefinition.ts
  src/components/questionary/questionaries/sample/StepsWizardWithoutReviewStepFactory.ts
  src/components/template/PreviewTemplateModal.tsx
  src/components/template/TemplateEditor.tsx
  src/context/UserContextProvider.tsx
  src/models/questionary/QuestionarySubmissionState.ts
  src/models/questionary/proposal/ProposalSubmissionState.ts
Labels: enhancement, review: please

#981 fix(ui): Swap NEXT and BACK buttons around
  src/components/shipments/ShippingInstructions.tsx
Labels: bug

#953 feat: add cypress test filter for ess and stfc tests
  cypress/integration/SEP.ts
  cypress/integration/appSettings.ts
  cypress/integration/calls.ts
  cypress/integration/eventLogs.ts
  cypress/integration/experiments.ts
  cypress/integration/features.ts
  cypress/integration/generalSeps.ts
  cypress/integration/generic_templates.ts
  cypress/integration/institutions.ts
  cypress/integration/instruments.ts
  cypress/integration/mobileViews.ts
  cypress/integration/pages.ts
  cypress/integration/peopleTable.ts
  cypress/integration/personal_information.ts
  cypress/integration/proposal_administration.ts
  cypress/integration/proposal_esi.ts
  cypress/integration/proposals.ts
  cypress/integration/questions.ts
  cypress/integration/samples.ts
  cypress/integration/scheduler.ts
  cypress/integration/settings.ts
  cypress/integration/shipments.ts
  cypress/integration/templates.ts
  cypress/integration/units.ts
  cypress/integration/user_administration.ts
  cypress/integration/user_spec.ts
  cypress/integration/visits.ts
  cypress/support/beforeRunHook.ts
  cypress/support/featureFlags.ts
  cypress/support/user.ts
  cypress/types/user.d.ts
Labels: enhancement, review: please

#968 add settings to control default proposal filters
  cypress/integration/appSettings.ts
  cypress/support/initialDBData.ts
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/review/ReviewerFilter.tsx
  src/generated/sdk.ts
Labels: review: please

#970 fix(questionary): Fixing the questionary state that wasn't updated when sample declaration or generic templates were modified
  cypress/integration/samples.ts
  src/components/proposal/ProposalContainer.tsx
  src/components/questionary/questionaryComponents/GenericTemplate/QuestionaryComponentGenericTemplate.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/QuestionaryComponentSampleDeclaration.tsx
  src/models/questionary/QuestionarySubmissionState.ts
Labels: bug, review: please

#989 refactor(graphql): rename query id params to have exact naming
  src/components/proposal/ProposalSummary.tsx
  src/components/settings/proposalWorkflow/ProposalWorkflowEditorModel.tsx
  src/components/user/UpdateUserInformation.tsx
  src/components/user/UpdateUserRoles.tsx
  src/generated/sdk.ts
  src/graphql/admin/getPageContent.graphql
  src/graphql/call/getCall.graphql
  src/graphql/settings/getProposalWorkflow.graphql
  src/graphql/user/getBasicUserDetails.graphql
  src/graphql/user/getUser.graphql
  src/graphql/user/getUserWithRoles.graphql
  src/hooks/admin/useGetPageContent.ts
  src/hooks/call/useCallData.ts
  src/hooks/user/useUserData.ts
  src/hooks/user/useUserWithRoles.ts
Labels: review: please, refactor

#992 feat: update instructions
  src/components/shipments/ShippingInstructions.tsx
Labels: enhancement

#990 creating github actions for e2e tests to run in stfc environment
  .github/workflows/test-build.yml
  .prettierignore
  cypress/integration/appSettings.ts
  cypress/integration/proposal_administration.ts
  docker-compose-stfc.e2e.yml
Labels: review: please

#988 feat: Add PDF templates
  .github/workflows/test-build.yml
  cypress/integration/pdf_templates.ts
  src/components/DashBoard.tsx
  src/components/menu/TemplateMenuListItem.tsx
  src/components/template/PdfTemplateEditor.tsx
  src/components/template/PdfTemplatesPage.tsx
  src/components/template/TemplatesTable.tsx
  src/generated/sdk.ts
  src/graphql/template/fragment.template.graphql
  src/graphql/template/getPdfTemplate.graphql
  src/graphql/template/updatePdfTemplate.graphql
  src/models/questionary/QuestionaryEditorModel.ts
Labels: enhancement, review: please

#996 feature: Attach custom PDF templates to calls
  src/components/call/CallGeneralInfo.tsx
  src/components/call/CreateUpdateCall.tsx
  src/generated/sdk.ts
  src/graphql/call/createCall.graphql
  src/graphql/call/fragment.call.graphql
  src/graphql/call/updateCall.graphql
Labels: review: please, Feature

#983 refactor(graphql): Split getFields into countries and nationalities queries
  .env.example
  src/components/institution/CreateUpdateInstitution.tsx
  src/components/user/SignUp.tsx
  src/components/user/UpdateUserInformation.tsx
  src/generated/sdk.ts
  src/graphql/user/getCountries.graphql
  src/graphql/user/getFields.graphql
  src/graphql/user/getNationalities.graphql
  src/hooks/user/useCountries.ts
  src/hooks/user/useNationalities.ts
Labels: review: please, refactor

#985 refactor(graphql): refactor getMetadata call
  src/components/common/FileUploadComponent.tsx
  src/components/questionary/questionaryComponents/FileUpload/FilesAnswerRenderer.tsx
  src/generated/sdk.ts
  src/graphql/questionary/fragment.fileMetadata.graphql
  src/graphql/questionary/getFileMetadata.graphql
  src/graphql/questionary/getFilesMetadata.graphql
  src/hooks/file/useFileMetadata.ts
  src/hooks/file/useFilesMetadata.ts
Labels: review: please, refactor

#1000 fix: Make branch detection less brittle
  .github/workflows/test-build.yml
Labels: bug, review: please

#1001 chore: balance load
  .github/workflows/test-build.yml
  cypress/integration/templates_advanced.ts
  cypress/integration/templates_basic.ts
Labels: chore

#998 feature: Add additional integer options
  cypress/integration/templates_basic.ts
  cypress/support/template.ts
  cypress/types/template.d.ts
  package-lock.json
  package.json
  src/components/questionary/questionaryComponents/NumberInput/QuestionNumberInputForm.tsx
  src/components/questionary/questionaryComponents/NumberInput/QuestionTemplateRelationNumberInputForm.tsx
  src/generated/sdk.ts
Labels: Feature

#999 Improve GraphQL error handling
  src/hooks/common/useDataApi.ts
Labels: review: please
