Repository UserOfficeProject/user-office-frontend, pull requests merged in 2022-03, with the labels that each got.

#776 chore(graphql-codegen): upgrade graphql-codegen packages to remove unnecessary template setting for overwriting the default maybeValue
  codegen_template.yml
  package-lock.json
  package.json
  src/generated/sdk.ts
Labels: review: please, chore

#772 feat: Allow to unsubmit proposal
  cypress/integration/proposals.ts
  src/components/common/TabPanel.tsx
  src/components/proposal/ProposalCreate.tsx
  src/components/proposal/ProposalSummary.tsx
  src/components/questionary/questionaries/proposal/ProposalQuestionaryWizardStep.ts
  src/graphql/proposal/updateProposal.graphql
Labels: enhancement

#764 Fix: More information to message when token has expired
  src/hooks/common/useDataApi.ts
Labels: Fix

#775 feat: Add start and end visit dates
  cypress/integration/visits.ts
  package.json
  src/components/questionary/questionaryComponents/VisitBasis/QuestionaryComponentVisitBasis.tsx
  src/components/questionary/questionaryComponents/VisitBasis/createVisitBasisValidationSchema.ts
  src/components/visit/CreateVisitRegistration.tsx
  src/components/visit/VisitRegistrationReview.tsx
  src/generated/sdk.ts
  src/graphql/visitRegistration/createVisitRegistration.graphql
  src/graphql/visitRegistration/fragment.visitRegistration.graphql
  src/graphql/visitRegistration/updateVisitRegistration.graphql
Labels: enhancement

#790 fix: remove unused menu item
  cypress/integration/calls.ts
  src/components/menu/MenuItems.tsx
Labels: bug

#782 refactor: make ProposalEsiDetails component reusable
  src/components/proposalEsi/ProposalEsiDetails.tsx
  src/components/proposalEsi/ProposalEsiReview.tsx
  src/components/questionary/questionaryComponents/ProposalEsiBasis/ProposalEsiDetailsButton.tsx
  src/hooks/common/ButtonWithDialog.tsx
Labels: refactor

#774 feat(SEP meeting components): Drag and drop UX improved with droppable area shown
  cypress/integration/SEP.ts
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
Labels: enhancement, review: please

#795 Fix: Show internal comments for instrument scientist
  src/components/questionary/QuestionaryDetails.tsx
  src/components/review/TechnicalReviewInformation.tsx
Labels: Fix

#796 fix: hide warning if local contact defined
  src/components/shipments/DeclareShipments.tsx
Labels: bug

#802 fix: revert lint speed update
  package.json
Labels: bug

#807 chore: Automatically update feature branch when base branch changes
  .github/workflows/autoupdate.yaml
Labels: review: please, chore

#763 fix: Hide incompatible calls
  cypress/integration/SEP.ts
  cypress/integration/calls.ts
  cypress/integration/generic_templates.ts
  cypress/integration/proposals.ts
  cypress/integration/samples.ts
  cypress/integration/settings.ts
  cypress/integration/templates.ts
  src/components/proposal/CallSelectModalOnProposalClone.tsx
  src/components/proposal/ProposalTable.tsx
Labels: bug, review: please

#808 Firefox does not set 'sameSite' by default for cookies
  src/context/UserContextProvider.tsx
Labels: review: please

#759 feat(units): Import/export units
  cypress/fixtures/units_export.json
  cypress/fixtures/units_import.json
  cypress/integration/templates.ts
  cypress/integration/units.ts
  src/components/DashBoard.tsx
  src/components/common/ConflictResolver.tsx
  src/components/common/SelectImportFile.tsx
  src/components/common/SuperMaterialTable.tsx
  src/components/proposal/ProposalTable.tsx
  src/components/review/AssignTechnicalReview.tsx
  src/components/settings/unitList/CreateUnit.tsx
  src/components/settings/unitList/UnitTable.tsx
  src/components/template/import/ConflictResolver.tsx
  src/components/template/import/ImportTemplatePage.tsx
  src/components/template/import/MergeReview.tsx
  src/components/unit/ImportUnitsPage.tsx
  src/generated/sdk.ts
  src/graphql/unit/createUnit.graphql
  src/graphql/unit/deleteUnit.graphql
  src/graphql/unit/fragment.unit.graphql
  src/graphql/unit/getQuanities.graphql
  src/graphql/unit/getUnits.graphql
  src/graphql/unit/getUnitsAsJson.graphql
  src/graphql/unit/importUnits.graphql
  src/graphql/unit/validateUnitsImport.graphql
  src/units/UnitMergeReview.tsx
Labels: enhancement, review: please

#810 fix: questions list not updated once question is deleted
  cypress/integration/questions.ts
  src/components/settings/unitList/UnitTable.tsx
  src/components/template/QuestionsPage.tsx
Labels: bug, review: please

#814 fix: improve error message when user is not found
  src/components/user/PeopleTable.tsx
  src/components/user/ProposalsPeopleTable.tsx
Labels: bug, review: please

#783 feat(SEPs): Add submitted checkbox inside SEP review grading for officer and SEP Chair/Secretary to be able to un-submit
  cypress/integration/SEP.ts
  cypress/integration/settings.ts
  src/components/DashBoard.tsx
  src/components/SEP/Proposals/SEPAssignedReviewersTable.tsx
  src/components/review/ProposalGrade.tsx
  src/generated/sdk.ts
  src/graphql/review/updateReview.graphql
Labels: enhancement

#816 feat: Add user information to error log
  src/components/App.tsx
Labels: enhancement

#803 feat: validate file upload types
  cypress/fixtures/file_without_ext
  cypress/fixtures/mp3_file.pdf
  cypress/fixtures/unidentifiable_file.pdf
  cypress/integration/templates.ts
  cypress/support/template.ts
  cypress/types/template.d.ts
  package-lock.json
  package.json
  src/components/common/FileUploadComponent.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionFileUploadForm.tsx
  src/components/questionary/questionaryComponents/FileUpload/QuestionTemplateRelationFileUploadForm.tsx
  src/hooks/common/useFileUpload.ts
Labels: enhancement, review: please

#801 fix: Fixing boolean filter not working
  cypress/fixtures/file_upload_test2.png
  cypress/fixtures/template_export.json
  cypress/integration/proposal_administration.ts
  cypress/integration/templates.ts
  cypress/support/initialDBData.ts
  src/components/questionary/questionaryComponents/Boolean/BooleanAnswerRenderer.tsx
  src/components/questionary/questionaryComponents/DatePicker/DateSearchCriteriaInput.tsx
  src/generated/sdk.ts
  src/graphql/template/createTempate.graphql
  src/hooks/proposal/useQuestionFilterQueryParams.tsx
Labels: bug, review: please

#768 Optimise user officer proposal table
  .gitignore
  cypress/integration/proposal_administration.ts
  cypress/integration/proposals.ts
  cypress/integration/settings.ts
  src/components/common/SuperMaterialTable.tsx
  src/components/proposal/ProposalTableOfficer.tsx
  src/generated/sdk.ts
  src/graphql/proposal/getProposalsCore.graphql
  src/hooks/proposal/useProposalsCoreData.ts
  src/hooks/proposal/useUserProposals.ts
Labels: review: please

#822 feat: add help page to front page of the user office
  src/components/pages/LoginHelpPage.tsx
  src/components/pages/PageEditor.tsx
  src/components/user/SignIn.tsx
  src/generated/sdk.ts
Labels: enhancement, review: please

#820 Query proposals by reference number
  src/generated/sdk.ts
Labels: review: please

#825 fix: Submitting shipment clears all fields, before it navigates
  src/components/questionary/questionaryComponents/ShipmentBasis/QuestionaryComponentShipmentBasis.tsx
Labels: bug

#824 fix: Links to be consistent and logo to be shown
  src/components/AppToolbar/AppToolbar.tsx
  src/components/DashBoard.tsx
  src/components/menu/MenuItems.tsx
  src/components/user/PeoplePage.tsx
Labels: bug

#826 fix: Add grading guide
  src/components/pages/GradeGuidePage.tsx
  src/components/pages/PageEditor.tsx
  src/components/review/ProposalGrade.tsx
  src/generated/sdk.ts
Labels: bug

#818 feat: Add other organisation in users profile update page
  cypress/integration/personal_information.ts
  cypress/integration/user_administration.ts
  src/components/user/UpdateUserInformation.tsx
  src/generated/sdk.ts
  src/graphql/user/updateUser.graphql
Labels: enhancement

#804 fix: improve questionary look and feel
  cypress/integration/personal_information.ts
  cypress/integration/shipments.ts
  src/components/common/CopyToClipboard.tsx
  src/components/proposal/ProposalContainer.tsx
  src/components/questionary/QuestionaryStepView.tsx
  src/components/questionary/questionaryComponents/Hint.tsx
  src/components/questionary/questionaryComponents/Interval/QuestionaryComponentInterval.tsx
  src/components/questionary/questionaryComponents/NumberInput/QuestionaryComponentNumberInput.tsx
  src/components/questionary/questionaryComponents/QuestionnairesList.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/QuestionaryComponentSampleDeclaration.tsx
  src/components/shipments/DeclareShipments.tsx
  src/generated/sdk.ts
Labels: bug

#834 Feat: Add PDF upload to technical review
  src/components/SEP/MeetingComponents/ProposalViewModal/SEPMeetingProposalViewModal.tsx
  src/components/SEP/MeetingComponents/ProposalViewModal/TechnicalReviewInfo.tsx
  src/components/common/FileUploadComponent.tsx
  src/components/review/ProposalTechnicalReview.tsx
  src/generated/sdk.ts
  src/graphql/proposal/fragment.coreTechnicalReview.graphql
  src/graphql/review/addTechnicalReview.graphql
  src/graphql/review/submitTechnicalReview.graphql
Labels: Feat

#829 feat: INSTUMENT_DELETED event added to general events
  src/generated/sdk.ts
Labels: enhancement, review: please

#823 fix(reviews): Use better and more stable tinymce editor content comparison for change detection and alert popup
  package-lock.json
  src/components/SEP/MeetingComponents/ProposalViewModal/FinalRankingForm.tsx
  src/components/proposal/ProposalAdmin.tsx
  src/components/review/ProposalGrade.tsx
  src/components/review/ProposalTechnicalReview.tsx
Labels: bug, review: please
