Repository UserOfficeProject/user-office-frontend, pull requests merged in 2022-05, with the labels that each got.

#873 feat: Remove access for SEP chair and secretary to un-submit or change submitted reviews
  cypress/integration/SEP.ts
  src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx
  src/components/review/ProposalGrade.tsx
Labels: enhancement, review: please

#872 feat: Use standard deviation as second sort parameter when initially sorted before ranking
  cypress/integration/SEP.ts
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
Labels: enhancement, review: please

#875 feat: Use settings formats instead of hardcoding into the initialDBData
  cypress/integration/calls.ts
  cypress/integration/eventLogs.ts
  cypress/integration/proposal_administration.ts
  cypress/integration/templates.ts
  cypress/integration/units.ts
  cypress/integration/user_spec.ts
  cypress/integration/visits.ts
  cypress/support/admin.ts
  cypress/support/beforeRunHook.ts
  cypress/support/index.ts
  cypress/support/initialDBData.ts
  cypress/types/admin.d.ts
Labels: enhancement, review: please

#880 fix: add copy to clipboar icon
  src/components/common/CopyToClipboard.tsx
  src/components/questionary/questionaryComponents/RichTextInput/RichTextInputRenderer.tsx
  src/components/template/AnswerCountDetails.tsx
  src/utils/truncateString.ts
Labels: bug

#876 feat: Improve technical review re-assign UI and filter list of reviewers to be only instrument scientsits and manager
  cypress/integration/instruments.ts
  src/components/review/AssignTechnicalReview.tsx
  src/components/review/ProposalReviewContent.tsx
  src/components/review/ProposalTechnicalReviewerAssignment.tsx
  src/components/settings/unitList/CreateUnit.tsx
  src/generated/sdk.ts
  src/graphql/proposal/getProposal.graphql
  src/hooks/proposal/useProposalData.ts
Labels: enhancement, review: please

#881 fix: questions page UX improvements
  cypress/integration/questions.ts
  src/components/questionary/questionaryComponents/QuestionFormShell.tsx
  src/components/template/AnswerCountDetails.tsx
  src/components/template/QuestionsPage.tsx
  src/components/template/TemplateCountDetails.tsx
  src/hooks/common/ButtonWithDialog.tsx
Labels: bug

#878 feat: added user officer features
  src/components/DashBoard.tsx
  src/components/menu/MenuItems.tsx
  src/components/menu/TemplateMenuListItem.tsx
  src/components/proposal/ProposalTableOfficer.tsx
  src/generated/sdk.ts
Labels: enhancement, review: please

#879 refactor: Refactor technical review and reassigning the review assignee. Also added technical review assignee to the officer and instrument scientist tables
  src/components/instrument/CreateUpdateInstrument.tsx
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/proposal/ProposalTableOfficer.tsx
  src/components/review/AssignTechnicalReview.tsx
  src/components/review/ProposalReviewContent.tsx
  src/components/review/ProposalTechnicalReview.tsx
  src/components/review/ProposalTechnicalReviewerAssignment.tsx
  src/components/review/TechnicalReviewInformation.tsx
  src/generated/sdk.ts
  src/graphql/proposal/fragment.coreTechnicalReview.graphql
  src/graphql/proposal/fragment.proposal.graphql
  src/graphql/proposal/getInstrumentScientistProposals.graphql
  src/graphql/proposal/getProposalsCore.graphql
  src/graphql/review/assignTechnicalReviewToUser.graphql
  src/utils/helperFunctions.ts
Labels: refactor

#883 feat(people table): Use orderBy and orderDirection to order users better when using the table column sort
  cypress/integration/peopleTable.ts
  cypress/integration/personal_information.ts
  cypress/integration/user_administration.ts
  src/components/institution/CreateUpdateInstitution.tsx
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/review/ProposalTableReviewer.tsx
  src/components/user/PeopleTable.tsx
  src/components/user/SignUp.tsx
  src/components/user/UpdateUserInformation.tsx
  src/generated/sdk.ts
  src/graphql/user/createUser.graphql
  src/graphql/user/getUsers.graphql
  src/graphql/user/updateUser.graphql
  src/hooks/user/useUsersData.ts
Labels: enhancement, review: please

#907 feat: Add unallocated time informational ribbon after last row in availability zone
  cypress/integration/SEP.ts
  src/components/SEP/MeetingComponents/SEPInstrumentProposalsTable.tsx
  src/components/common/CopyToClipboard.tsx
  src/components/questionary/questionaryComponents/DatePicker/DateAnswerRenderer.tsx
Labels: enhancement

#914 feat(auth): As a user I want single sign on with PING
  src/components/App.tsx
  src/components/user/ExternalAuth.tsx
  src/utils/getPingAuthTokenFromCallbackUrl.tsx
Labels: enhancement, review: please

#910 feat: Add features page with possibility to enable and disable features
  src/components/App.tsx
  src/components/DashBoard.tsx
  src/components/call/CallGeneralInfo.tsx
  src/components/menu/MenuItems.tsx
  src/components/menu/TemplateMenuListItem.tsx
  src/components/pages/OverviewPage.tsx
  src/components/proposal/ProposalTableInstrumentScientist.tsx
  src/components/proposal/ProposalTableOfficer.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/QuestionSampleDeclarationForm.tsx
  src/components/questionary/questionaryComponents/SampleDeclaration/QuestionTemplateRelationSampleDeclarationForm.tsx
  src/components/settings/features/FeaturesPage.tsx
  src/components/settings/features/FeaturesTable.tsx
  src/components/user/PeopleTable.tsx
  src/components/user/ProposalsPeopleTable.tsx
  src/context/FeatureContextProvider.tsx
  src/generated/sdk.ts
  src/graphql/settings/updateFeatures.graphql
  src/hooks/admin/useFeatures.ts
  src/utils/helperFunctions.ts
Labels: enhancement, review: please

#901 feat: added linter workflow for GitHub actions
  .github/workflows/lint.yml
  .prettierignore
  .unimportedrc.json
  cypress/fixtures/example.json
  cypress/fixtures/template_export.json
  cypress/fixtures/template_import.json
  cypress/fixtures/units_export.json
  cypress/fixtures/units_import.json
  src/serviceWorker.js
Labels: enhancement, review: please
